<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="AuctionWebTest_googlechrome"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="28.512">
  <properties />
            <testcase name="SecondCarTransferVerify" time="27.073" classname="com.auction.testcase.secondcar.SecondCarTransferReportTest">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  com.auction.page.NextNodePopupPage.NextNodePopup(NextNodePopupPage.java:135)
  com.auction.page.secondcar.MyTaskSecondCarTransferReportDetailToDo.SecondCarTransferVerifySubmit(MyTaskSecondCarTransferReportDetailToDo.java:51)
  com.auction.page.secondcar.MyTaskSecondCarTransferReportDetailToDo.SecondCarTransferVerifySubmit(MyTaskSecondCarTransferReportDetailToDo.java:60)
  com.auction.testcase.secondcar.SecondCarTransferReportTest.SecondCarTransferVerify(SecondCarTransferReportTest.java:83)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testLogin" time="1.439" classname="com.auction.testcase.secondcar.SecondCarTransferReportTest" />
      
</testsuite>
